version: '3.8'

services:
  # pgvector:
  #   image: ankane/pgvector
  #   environment:
  #     POSTGRES_PASSWORD: langchain
  #     POSTGRES_USER: langchain
  #     POSTGRES_DB: langchain
  #   ports:
  #     - "5432:5432"

  question_service:
    build:
      context: ./core/chat
      dockerfile: Dockerfile
    image: question-app
    depends_on:
      - pgvector
    environment:
      DATABASE_URL: postgresql+psycopg://langchain:langchain@localhost:5432/langchain
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - /mnt/datos/desarrollo/huggingface-models:/app/models

  ui_service:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: ui-app
    depends_on:
      - question_service
    environment:
      DATABASE_URL: postgresql+psycopg://langchain:langchain@localhost:5432/langchain
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - /mnt/datos/desarrollo/huggingface-models:/app/models    
